from __future__ import annotations

import re
from typing import Any, Dict, Optional


SECTION_LABELS = [
    "discharge diagnosis",
    "diagnosis",
    "hospital course",
    "discharge medications",
    "medications on discharge",
    "medications",
    "follow-up",
    "follow up",
]


def _clean_text(text: Any, strip_terminal_punctuation: bool = False) -> str:
    value = " ".join(str(text or "").split()).strip()

    if strip_terminal_punctuation:
        value = value.rstrip(" .!?;:")

    return value


def _first_match(text: str, patterns: list[str]) -> Optional[str]:
    for pattern in patterns:
        match = re.search(
            pattern,
            text,
            flags=re.IGNORECASE | re.MULTILINE,
        )
        if match:
            value = _clean_text(match.group(1))
            if value:
                return value

    return None


def _extract_identity(text: str) -> Dict[str, Optional[str]]:
    name = _first_match(
        text,
        [
            r"\bpatient\s*[:\-]?\s*"
            r"([A-Za-z][A-Za-z .'-]{1,60}?)"
            r"(?=\s+\bdischarge\s+date\b"
            r"|\s+\bdate\b"
            r"|\s+\badmission\b"
            r"|\s+\bdischarge\b|$)",
        ],
    )

    date = _first_match(
        text,
        [
            r"\bdischarge\s+date\s*[:\-]?\s*"
            r"(\d{1,2}[/-]\d{1,2}[/-]\d{2,4})",
            r"\bdate\s*[:\-]?\s*"
            r"(\d{1,2}[/-]\d{1,2}[/-]\d{2,4})",
        ],
    )

    return {
        "patient_name": name,
        "date": date,
    }


def _extract_section(
    text: str,
    labels: list[str],
    strip_terminal_punctuation: bool = False,
) -> Optional[str]:
    """
    Extract text after a section label until the next known section label.
    Works with flattened OCR text and normal line-based OCR.
    """
    label_pattern = "|".join(
        re.escape(label)
        for label in sorted(labels, key=len, reverse=True)
    )

    pattern = (
        rf"\b(?:{label_pattern})\b"
        rf"\s*[:\-]?\s*(.*?)"
        rf"(?=\s+\b(?:{label_pattern})\b\s*[:\-]?\s*|$)"
    )

    match = re.search(
        pattern,
        text,
        flags=re.IGNORECASE | re.DOTALL,
    )

    if not match:
        return None

    value = _clean_text(
        match.group(1),
        strip_terminal_punctuation=strip_terminal_punctuation,
    )

    return value or None


def extract_discharge_summary(ocr_result: Dict[str, Any]) -> Dict[str, Any]:
    """
    Deterministically extract facts from a discharge-summary OCR result.

    Fields:
      - patient_name
      - discharge date
      - discharge diagnosis
      - hospital course
      - discharge medications
      - follow-up

    No diagnosis, treatment recommendation, or clinical interpretation is
    generated by this extractor.
    """
    if not isinstance(ocr_result, dict):
        raise TypeError("ocr_result must be a dictionary")

    raw_text = _clean_text(
        ocr_result.get("raw_text")
        if ocr_result.get("raw_text") is not None
        else ocr_result.get("text")
    )

    document_type = str(
        ocr_result.get("document_type") or ""
    ).strip().lower()

    confidence = (
        ocr_result.get("ocr_confidence")
        if ocr_result.get("ocr_confidence") is not None
        else ocr_result.get("mean_confidence")
    )

    identity = _extract_identity(raw_text)

    diagnosis = _extract_section(
        raw_text,
        [
            "discharge diagnosis",
            "hospital course",
            "discharge medications",
            "medications on discharge",
            "follow-up",
            "follow up",
        ],
    )

    if diagnosis is not None and diagnosis.lower().startswith("diagnosis"):
        diagnosis = diagnosis.split(":", 1)[-1].strip()

    hospital_course = _extract_section(
        raw_text,
        [
            "hospital course",
            "discharge medications",
            "medications on discharge",
            "medications",
            "follow-up",
            "follow up",
        ],
    )

    discharge_medications = _extract_section(
        raw_text,
        [
            "discharge medications",
            "medications on discharge",
            "medications",
            "follow-up",
            "follow up",
        ],
    )

    # Normalize the terminal full stop so the existing project test/API
    # contract remains stable while raw OCR text stays fully preserved.
    follow_up = _extract_section(
        raw_text,
        ["follow-up", "follow up"],
        strip_terminal_punctuation=True,
    )

    if diagnosis is None:
        diagnosis = _first_match(
            raw_text,
            [
                r"\bdischarge\s+diagnosis\s*[:\-]\s*(.*?)(?="
                r"\s+\bhospital\s+course\b"
                r"|\s+\bdischarge\s+medications?\b"
                r"|\s+\bfollow[- ]?up\b|$)",
                r"\bdiagnosis\s*[:\-]\s*(.*?)(?="
                r"\s+\bhospital\s+course\b"
                r"|\s+\bdischarge\s+medications?\b"
                r"|\s+\bfollow[- ]?up\b|$)",
            ],
        )

    if hospital_course is None:
        hospital_course = _first_match(
            raw_text,
            [
                r"\bhospital\s+course\s*[:\-]\s*(.*?)(?="
                r"\s+\bdischarge\s+medications?\b"
                r"|\s+\bmedications?\s+on\s+discharge\b"
                r"|\s+\bfollow[- ]?up\b|$)",
            ],
        )

    if discharge_medications is None:
        discharge_medications = _first_match(
            raw_text,
            [
                r"\bdischarge\s+medications?\s*[:\-]\s*(.*?)(?="
                r"\s+\bfollow[- ]?up\b|$)",
                r"\bmedications?\s+on\s+discharge\s*[:\-]\s*(.*?)(?="
                r"\s+\bfollow[- ]?up\b|$)",
            ],
        )

    if follow_up is None:
        follow_up = _first_match(
            raw_text,
            [
                r"\bfollow[- ]?up\s*[:\-]?\s*(.*)$",
            ],
        )
        if follow_up is not None:
            follow_up = _clean_text(
                follow_up,
                strip_terminal_punctuation=True,
            )

    review_reasons: list[str] = []

    if document_type not in ("discharge_summary", ""):
        review_reasons.append(
            f"Document type was reported as '{document_type}', "
            "not discharge_summary."
        )

    if identity["patient_name"] is None:
        review_reasons.append("Patient name was not extracted.")

    if identity["date"] is None:
        review_reasons.append("Discharge date was not extracted.")

    if diagnosis is None:
        review_reasons.append("Discharge diagnosis was not extracted.")

    if (
        hospital_course is None
        and discharge_medications is None
        and follow_up is None
    ):
        review_reasons.append(
            "No discharge details were confidently extracted."
        )

    for reason in ocr_result.get("review_reasons") or []:
        if reason not in review_reasons:
            review_reasons.append(reason)

    manual_review_required = bool(
        ocr_result.get("manual_review_required", False)
        or review_reasons
    )

    return {
        "status": "success" if raw_text and diagnosis else "error",
        "document_type": "discharge_summary",
        "patient_name": identity["patient_name"],
        "date": identity["date"],
        "structured_data": {
            "document_type": "discharge_summary",
            "patient_name": identity["patient_name"],
            "date": identity["date"],
            "diagnosis": diagnosis,
            "hospital_course": hospital_course,
            "discharge_medications": discharge_medications,
            "follow_up": follow_up,
        },
        "raw_text": raw_text,
        "ocr_confidence": confidence,
        "manual_review_required": manual_review_required,
        "review_reasons": review_reasons,
    }


if __name__ == "__main__":
    print("Use extract_discharge_summary(ocr_result) from Python.")
