from __future__ import annotations

import shutil
import zipfile
from pathlib import Path


# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

# This script lives at:
#   Aurora/backend/scripts/import_teammate_ai.py
#
# Therefore:
#   parents[0] = scripts/
#   parents[1] = backend/
#
# Using the script location instead of the current working directory prevents
# accidental creation of:
#   backend/backend/ai/
BACKEND_ROOT = Path(__file__).resolve().parents[1]

SOURCE_ZIP = (
    Path("/home/niggatron/Downloads")
    / "SIH26_Aurora_compatible.zip"
)

AI_ROOT = BACKEND_ROOT / "ai"
TEMP_ROOT = BACKEND_ROOT / ".teammate_ai_import"


# ---------------------------------------------------------------------------
# Files to import
# ---------------------------------------------------------------------------

# Production AI modules we actually want from the teammate package.
#
# Deliberately excluded:
#   ai_engine.py
#   clinical_service.py
#   clinical_engine.py
#   complaint_router.py
#   aurora_integration.py
#
# Those belong to the old questionnaire / clinical-session architecture
# that we are rebuilding rather than carrying forward.
IMPORT_MAP: dict[str, str] = {
    # OCR
    "document_ocr.py": "ocr/engine.py",

    # Document processing
    "document_extractor.py": "documents/extractor.py",
    "lab_document_extractor.py": "documents/laboratory.py",
    "discharge_document_extractor.py": "documents/discharge.py",
    "medical_document_pipeline.py": "documents/pipeline.py",
    "document_clinical_bridge.py": "documents/bridge.py",

    # Clinical intelligence
    "clinical_evidence.py": "clinical/evidence.py",
    "clinical_discrepancy.py": "clinical/discrepancy.py",
    "clinical_timeline.py": "clinical/timeline.py",
    "medication_safety.py": "clinical/medication_safety.py",
    "physician_summary.py": "clinical/summary.py",

    # Voice
    "voice_asr.py": "voice/asr.py",
}


PACKAGE_DIRS = (
    AI_ROOT,
    AI_ROOT / "interview",
    AI_ROOT / "ocr",
    AI_ROOT / "documents",
    AI_ROOT / "clinical",
    AI_ROOT / "voice",
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def find_zip_member(
    archive: zipfile.ZipFile,
    filename: str,
) -> str | None:
    """
    Find a file in the ZIP regardless of the directory prefix used by the
    archive.

    For example, all of these can match document_ocr.py:

        document_ocr.py
        src/document_ocr.py
        Aurora/document_ocr.py
        package/backend/document_ocr.py
    """
    filename = filename.replace("\\", "/")

    exact_matches = [
        member
        for member in archive.namelist()
        if member.replace("\\", "/") == filename
    ]

    if exact_matches:
        return exact_matches[0]

    basename_matches = [
        member
        for member in archive.namelist()
        if Path(member.replace("\\", "/")).name == filename
    ]

    if not basename_matches:
        return None

    if len(basename_matches) > 1:
        print(
            f"WARNING: multiple matches found for {filename!r}:"
        )
        for match in basename_matches:
            print(f"  - {match}")

        # Prefer the shortest path because it is usually the package-level
        # source file rather than a duplicate in a nested test/example tree.
        basename_matches.sort(key=lambda value: len(Path(value).parts))

    return basename_matches[0]


def ensure_package_dirs() -> None:
    """Create the required AI package directories."""
    for directory in PACKAGE_DIRS:
        directory.mkdir(parents=True, exist_ok=True)


def create_package_init(directory: Path) -> None:
    """
    Create __init__.py if one does not already exist.

    We deliberately do not overwrite an existing file.
    """
    init_file = directory / "__init__.py"

    if not init_file.exists():
        init_file.write_text(
            '"""Aurora AI package."""\n',
            encoding="utf-8",
        )


def clean_previous_import() -> None:
    """
    Remove only files previously generated by this importer.

    Do not blindly delete the complete ai/ directory because it may already
    contain manually created interview code.
    """
    for relative_path in IMPORT_MAP.values():
        destination = AI_ROOT / relative_path

        if destination.exists():
            destination.unlink()
            print(f"Removed previous import: {
                  destination.relative_to(BACKEND_ROOT)}")


def extract_selected_files() -> None:
    """Extract only the explicitly approved teammate modules."""
    if not SOURCE_ZIP.exists():
        raise FileNotFoundError(
            f"Teammate ZIP not found:\n{SOURCE_ZIP}"
        )

    AI_ROOT.mkdir(parents=True, exist_ok=True)

    with zipfile.ZipFile(SOURCE_ZIP, "r") as archive:
        for source_name, relative_destination in IMPORT_MAP.items():
            member = find_zip_member(archive, source_name)

            if member is None:
                print(
                    f"WARNING: {source_name} was not found in the teammate ZIP"
                )
                continue

            destination = AI_ROOT / relative_destination
            destination.parent.mkdir(parents=True, exist_ok=True)

            with archive.open(member) as source:
                with destination.open("wb") as target:
                    shutil.copyfileobj(source, target)

            print(
                f"Imported: {source_name}"
                f" -> {destination.relative_to(BACKEND_ROOT)}"
            )


def write_package_inits() -> None:
    """Ensure all imported AI subdirectories are Python packages."""
    for directory in PACKAGE_DIRS:
        create_package_init(directory)


def print_result() -> None:
    """Print the final AI tree for verification."""
    print()
    print("=" * 72)
    print("Aurora AI import complete")
    print("=" * 72)
    print(f"Backend root : {BACKEND_ROOT}")
    print(f"AI root      : {AI_ROOT}")
    print()

    files = sorted(
        path
        for path in AI_ROOT.rglob("*")
        if path.is_file()
    )

    if not files:
        print("No AI files were imported.")
        return

    for path in files:
        print(path.relative_to(BACKEND_ROOT))


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> None:
    print("Aurora teammate AI importer")
    print()
    print(f"Backend root: {BACKEND_ROOT}")
    print(f"Source ZIP  : {SOURCE_ZIP}")
    print(f"AI target   : {AI_ROOT}")
    print()

    clean_previous_import()
    ensure_package_dirs()
    extract_selected_files()
    write_package_inits()
    print_result()


if __name__ == "__main__":
    main()
